apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycompletepipeline:1.0.0-37
spec:
  selector:
    matchLabels:
      app: mycompletepipeline:1.0.0-37
  template:
    metadata:
      labels:
        app: mycompletepipeline:1.0.0-37
    spec:
      containers:
        - name: mycompletepipeline:1.0.0-37
          image: wasraz/mycompletepipeline:1.0.0-37
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080