apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycompleteCICDpipeline-deployment
spec:
  selector:
    matchLabels:
      app: mycompleteCICDpipeline-app
  template:
    metadata:
      labels:
        app: mycompleteCICDpipeline-app
    spec:
      containers:
        - name: mycompletepipeline-app
          image: wasraz/mycompletepipeline:1.0.0-37
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080