apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycompletecicdpipeline-deployment
spec:
  selector:
    matchLabels:
      app: mycompletecicdpipeline-app
  template:
    metadata:
      labels:
        app: mycompletecicdpipeline-app
    spec:
      containers:
        - name: mycompletecicdpipeline-app
          image: wasraz/mycompletepipeline:1.0.0-41
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080