apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycompletepipeline-deployment
spec:
  selector:
    matchLabels:
      app: mycompletepipeline-app
  template:
    metadata:
      labels:
        app: mycompletepipeline-app
    spec:
      containers:
        - name: mycompletepipeline-app
          image: wasraz/mycompletepipeline:1.0.0-28
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080